### ISSUE TITLE
m-un-push and margin left

### ISSUE THREAD

**Issue by danieledistanio** [lucasgruwez/waffle-grid#15]
Hi Lucas,

thank you for Waffle, it is a bless for me! 👍 

I'm updating to 1.3.4 and I see that if I have:

- grid
- - row
- - - col col-5-of-12 push-1-of-12 col-m-4-of-4 m-un-push
- - - col col-5-of-12 col-m-4-of-4

to have a 1551 layout, I get an asymmetry when layout is reduced to "m".

This happens because "col" has a margin:10px, but m-un-push is setting margin: 0;

In my case this is solved by replacing margin: inherit; but I understand milage may vary

(no dev here, sorry)

Hope this help,
Daniele

**Comment by lucasgruwez** [comment]
Hi Daniele,

Thank you very much for pointing out this problem to me! I'm sorry if it took me a bit of time to answer, but I have been busy lately.

I have however found what was causing the problem: I use the margin for the gutter, and I completely remove it when you un-push an element. I am working on fixing that issue now, and a fix should be out pretty soon

Thanks again for the help,
Lucas

**Comment by lucasgruwez** [comment]
The issue should now be fixed!  

Thanks again for helping out, I will just add a demo of `un-push` to the homepage, and the wiki before closing this issue.

Lucas

**Comment by lucasgruwez** [comment]
There is now a demo on the homepage and I have also added `un-push` to the wiki

Lucas
