### ISSUE TITLE
Scope generic-most classes

### ISSUE THREAD

**Issue by adi-works** [lucasgruwez/waffle-grid#17]
Hi,

I'm using this in SPA context and as a global dependency that isn't getting scoped by setting a `scoped` attribute, it's affecting generic classes of scoped components with classes like `center`, `right`, etc'. If you could give an option to scope these, it solves my issue.

**Comment by lucasgruwez** [comment]
Hi, 

I'm am not sure what you mean with this... Could you give an example snippet so that I can better understand this issue?
Thanks for contributing, and sorry for taking so long to respond, but I have been a bit busy lately.

Lucas
