### ISSUE TITLE
What happened to `$m-columns`?

### ISSUE THREAD

**Issue by adi-works** [lucasgruwez/waffle-grid#18]
It seems the docs are no long coherent as this variable is nowhere to be found. How do you generate different columns for mobile now?

**Comment by lucasgruwez** [comment]
Hi @adi518,

To define different columns on mobile, you have to use the `$breakpoints` variable. For example, if you want to have `.col-m-n-of-3` and `.col-m-n-of-5` on mobile, you should define the breakpoints variable as: 
```sass
$breakpoints: (
	m: (840px, (3, 5)),
)
```
This variable is an object, that has the breakpoint names as keys (`m` in this case), and `( screen-width , (col-amount-1, col-amount-2...) )`, as a value. The [source code](https://github.com/lucasgruwez/waffle-grid/blob/master/src/waffle-grid.scss) has a quick explanation for each variable in the comments.

Hope this helps, and thanks for pointing out the outdated docs! I'll fix them ASAP.

Lucas
