### ISSUE TITLE
Helper should allow prefixing

### ISSUE THREAD

**Issue by santiDotIO** [lucasgruwez/waffle-grid#21]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] feature request
  - [ ] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Most of the grid classes can be customized with the exception of the helper clases
https://github.com/lucasgruwez/waffle-grid/wiki/Using-the-grid#helper-classes

* **What is the current behavior?**
Currently you cannot prefix these classes which creates conflicts with other packages.

* **What is the expected behavior?**
Allow to have a scss variable you can set to prefix helper classes/

**Comment by lucasgruwez** [comment]
Ah yes, I can see how that would conflict with other libraries...
I like the idea of adding an scss variable to prefix the helper classes and will implement it ASAP.

**Comment by lucasgruwez** [comment]
Done! v1.3.6, use `$helper-prefix` to set the prefix for the helper classes, for example, if its set to `"waffle-"`, the classes would be `.waffle-center`, `.waffle-m-hide`, etc...

**Comment by santiDotIO** [comment]
@lucasgruwez Awesome! thank you!
