### ISSUE TITLE
[REQUEST] Publish to Bower

### ISSUE THREAD

**Issue by NuroDev** [lucasgruwez/waffle-grid#7]
Love the framework, and it's all good having it available on npm. But since it's CSS framework, would be super helpful to have it also available via [bower](https://bower.io).
Would be great to have a it as a bower dependency 😄

**Comment by lucasgruwez** [comment]
Hi there,

Adding the framework to bower has been on the [todo project](https://github.com/lucasgruwez/waffle-grid/projects/1) for a couple of days now. I haven't been able to do it yet as I have been busy with other things. 

I appreciate your request and I will add the waffle grid to bower shortly.

Lucas

**Comment by lucasgruwez** [comment]
Added the waffle-grid to Bower. You can now install it with:
```
$ bower install waffle-grid
```

Thanks again for the request.

Lucas
